### ISSUE TITLE
Summary Plugin - incorrect marker syntax

### ISSUE THREAD

**Issue by petsy** [finklabs/buccaneer#1]
Tested petsy_2014, bitbucket commit 1e17e39, Stand 8.2.2015

Currently blogposts have the following summary marker: 
This is markdown syntax, which is incorrect in rst documents in use.

Incorrect marker needs to be exchanged in ALL blogposts with the following correct rst marker: 
.. END_SUMMARY

**Comment by markfink** [comment]
this is a problem specific to your content.
(please note: I updated your content and pushed to your content repository)
