### ISSUE TITLE
LICENSE file is missing.

### ISSUE THREAD

**Issue by almet** [finklabs/buccaneer#19]
Hey, while reading [the initial change commit](https://github.com/finklabs/buccaneer/commit/e606a189286a3a078a6901e99af47ca79ea94663) I found out that the LICENSE file was removed, probably by accident.

Since this is based on some work by pelican folks, I believe it should be released under the same license. Can please add it back? Thanks!

**Comment by markfink** [comment]
https://github.com/finklabs/buccaneer/commit/d37261e945487b281ea0bfa45d45c3e0eff50ff8
Added the file back.
