### ISSUE TITLE
Summary Plugin - no "read more" link

### ISSUE THREAD

**Issue by petsy** [finklabs/buccaneer#2]
Tested petsy_2014, bitbucket commit 1e17e39, Stand 8.2.2015

The summary misses a "(read more...) link in order to view the whole blogpost.

**Comment by markfink** [comment]
I think the read_more_link plugin does exactly that. I am going to add the plugin asap.

**Comment by markfink** [comment]
on second thought I prefer the solution of adding the "read-more" link to the sites article-info template. this is exactly how I implemented it. For now I did not port the read_more_link plugin. Lets keep this idea as a fallback solution.

**Comment by petsy** [comment]
works fine, thank you.
