### ISSUE TITLE
SEO Title and SEO Description missing

### ISSUE THREAD

**Issue by petsy** [finklabs/buccaneer#3]
Tested petsy_2014, bitbucket commit 1e17e39, Stand 8.2.2015

Blogposts and pages have the following individual meta information in the content:
: seotitle:
: seodescription:

Example:
:seotitle: Children Photography | Augsburg, Munich, Ammersee, Starnberg, Landsberg
:seodescription: Petsy Fink is a professional fine art children photographer. Augsburg, Munich, Ammersee, Starnberg, Landsberg, Allgäu

This results in the source page to:
<title>Children Photography | Augsburg, Munich, Ammersee, Starnberg, Landsberg</title>
<meta name="description" content="Petsy Fink is a professional fine art children photographer. Augsburg, Munich, Ammersee, Starnberg, Landsberg, Allgäu."/>

Both entries are missing in all pages and blogposts. 

All pages and blogposts show incorrectly:
<title>Ein mehrsprachiges Beispiel</title>
<title>a buccaneer sample</title>
No meta descriptions.

**Comment by markfink** [comment]
seems like this is an issue related to your content

**Comment by petsy** [comment]
moved issue to bitbucket
