### ISSUE TITLE
develop_server.sh does not refresh changes

### ISSUE THREAD

**Issue by petsy** [finklabs/buccaneer#5]
Tested petsy_2014, bitbucket commit 1e17e39, Stand 8.2.2015

9.2.2015: Made changes to existing content of a blogpost; added a new blogpost; added a new page.
Built was successful.
Changes do not show in localhost.

Terminal shows after starting ssh server:

CRITICAL: global name 'time' is not defined
Traceback (most recent call last):
  File "/home/petsy/Desktop/repos/venv/bin/buccaneer", line 9, in <module>
    load_entry_point('buccaneer==3.6.24', 'console_scripts', 'buccaneer')()
  File "/home/petsy/Desktop/repos/venv/local/lib/python2.7/site-packages/buccaneer/__init__.py", line 84, in main
    time.sleep(.5)  # sleep to avoid cpu load
NameError: global name 'time' is not defined

**Comment by markfink** [comment]
already fixed the "NameError: global name 'time' is not defined" issue. the next buccaneer release is going to contain this fix. I need to further analyse the "update" issue. This appears to be cache related.

**Comment by markfink** [comment]
"NameError: global name 'time' is not defined" was the root cause.

**Comment by petsy** [comment]
works fine, thank you.
